// Code generated by protoc-gen-go.
// source: client_packet.proto
// DO NOT EDIT!

/*
Package packet is a generated protocol buffer package.

It is generated from these files:
	client_packet.proto
	shared.proto

It has these top-level messages:
	PacketInitialization
	PacketReady
	PacketCallerSend
	PacketCallerRecv
	PacketCalleeRecv
	PacketCalleeSend
	InvocationId
	Invocation
*/
package packet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// initialization packet
//
// client will send a Init once connection established.
// client has to declare it's mode, either a 'caller', who sends invocations, or a 'callee', who execute invocations and returns values.
type PacketInitialization struct {
	Mode     ClientMode `protobuf:"varint,1,opt,name=mode,enum=sodibus.ClientMode" json:"mode,omitempty"`
	Provides []string   `protobuf:"bytes,2,rep,name=provides" json:"provides,omitempty"`
}

func (m *PacketInitialization) Reset()                    { *m = PacketInitialization{} }
func (m *PacketInitialization) String() string            { return proto.CompactTextString(m) }
func (*PacketInitialization) ProtoMessage()               {}
func (*PacketInitialization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PacketInitialization) GetMode() ClientMode {
	if m != nil {
		return m.Mode
	}
	return ClientMode_CALLER
}

func (m *PacketInitialization) GetProvides() []string {
	if m != nil {
		return m.Provides
	}
	return nil
}

// ready packet
//
// SODIBus will send a PacketReady after initialization ready
type PacketReady struct {
	Mode     ClientMode `protobuf:"varint,1,opt,name=mode,enum=sodibus.ClientMode" json:"mode,omitempty"`
	NodeId   uint64     `protobuf:"varint,2,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	ClientId uint64     `protobuf:"varint,3,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
}

func (m *PacketReady) Reset()                    { *m = PacketReady{} }
func (m *PacketReady) String() string            { return proto.CompactTextString(m) }
func (*PacketReady) ProtoMessage()               {}
func (*PacketReady) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PacketReady) GetMode() ClientMode {
	if m != nil {
		return m.Mode
	}
	return ClientMode_CALLER
}

func (m *PacketReady) GetNodeId() uint64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *PacketReady) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

// invocation packet
//
// caller client send invocation packet when it wants to invoke a service
type PacketCallerSend struct {
	Id         uint64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Invocation *Invocation `protobuf:"bytes,2,opt,name=invocation" json:"invocation,omitempty"`
}

func (m *PacketCallerSend) Reset()                    { *m = PacketCallerSend{} }
func (m *PacketCallerSend) String() string            { return proto.CompactTextString(m) }
func (*PacketCallerSend) ProtoMessage()               {}
func (*PacketCallerSend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PacketCallerSend) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PacketCallerSend) GetInvocation() *Invocation {
	if m != nil {
		return m.Invocation
	}
	return nil
}

// invocation result packet
//
// caller client send receives result packet when invocation finished
type PacketCallerRecv struct {
	Id     uint64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Code   ErrorCode `protobuf:"varint,2,opt,name=code,enum=sodibus.ErrorCode" json:"code,omitempty"`
	Result string    `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *PacketCallerRecv) Reset()                    { *m = PacketCallerRecv{} }
func (m *PacketCallerRecv) String() string            { return proto.CompactTextString(m) }
func (*PacketCallerRecv) ProtoMessage()               {}
func (*PacketCallerRecv) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PacketCallerRecv) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PacketCallerRecv) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

func (m *PacketCallerRecv) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// invocation recieved by Callee
type PacketCalleeRecv struct {
	Id         *InvocationId `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Invocation *Invocation   `protobuf:"bytes,2,opt,name=invocation" json:"invocation,omitempty"`
}

func (m *PacketCalleeRecv) Reset()                    { *m = PacketCalleeRecv{} }
func (m *PacketCalleeRecv) String() string            { return proto.CompactTextString(m) }
func (*PacketCalleeRecv) ProtoMessage()               {}
func (*PacketCalleeRecv) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PacketCalleeRecv) GetId() *InvocationId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PacketCalleeRecv) GetInvocation() *Invocation {
	if m != nil {
		return m.Invocation
	}
	return nil
}

// invocation result sent by Callee
type PacketCalleeSend struct {
	Id     *InvocationId `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Result string        `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *PacketCalleeSend) Reset()                    { *m = PacketCalleeSend{} }
func (m *PacketCalleeSend) String() string            { return proto.CompactTextString(m) }
func (*PacketCalleeSend) ProtoMessage()               {}
func (*PacketCalleeSend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PacketCalleeSend) GetId() *InvocationId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PacketCalleeSend) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*PacketInitialization)(nil), "sodibus.PacketInitialization")
	proto.RegisterType((*PacketReady)(nil), "sodibus.PacketReady")
	proto.RegisterType((*PacketCallerSend)(nil), "sodibus.PacketCallerSend")
	proto.RegisterType((*PacketCallerRecv)(nil), "sodibus.PacketCallerRecv")
	proto.RegisterType((*PacketCalleeRecv)(nil), "sodibus.PacketCalleeRecv")
	proto.RegisterType((*PacketCalleeSend)(nil), "sodibus.PacketCalleeSend")
}

func init() { proto.RegisterFile("client_packet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6b, 0xc2, 0x30,
	0x14, 0xc7, 0xb1, 0x96, 0xaa, 0xcf, 0x21, 0x23, 0xee, 0x47, 0xd1, 0x8b, 0x14, 0xdc, 0x3c, 0xf5,
	0xa0, 0xff, 0xc1, 0x64, 0x87, 0x1e, 0x06, 0x5b, 0x76, 0x18, 0x6c, 0x07, 0x89, 0x7d, 0x8f, 0x2d,
	0xac, 0x26, 0x92, 0x44, 0xc1, 0xfd, 0xf5, 0xc3, 0x54, 0x3a, 0xcb, 0x76, 0x90, 0x9d, 0xca, 0xcb,
	0x7b, 0xfd, 0x7c, 0xdf, 0x27, 0x04, 0xfa, 0x79, 0x21, 0x49, 0xb9, 0xc5, 0x5a, 0xe4, 0x9f, 0xe4,
	0xd2, 0xb5, 0xd1, 0x4e, 0xb3, 0x96, 0xd5, 0x28, 0x97, 0x1b, 0x3b, 0x38, 0xb3, 0x1f, 0xc2, 0x10,
	0x96, 0xc7, 0xc9, 0x1b, 0x5c, 0x3c, 0xfa, 0xb1, 0x4c, 0x49, 0x27, 0x45, 0x21, 0xbf, 0x84, 0x93,
	0x5a, 0xb1, 0x5b, 0x08, 0x57, 0x1a, 0x29, 0x6e, 0x8c, 0x1a, 0x93, 0xde, 0xb4, 0x9f, 0x1e, 0xfe,
	0x4e, 0xe7, 0x1e, 0xfd, 0xa0, 0x91, 0xb8, 0x1f, 0x60, 0x03, 0x68, 0xaf, 0x8d, 0xde, 0x4a, 0x24,
	0x1b, 0x07, 0xa3, 0xe6, 0xa4, 0xc3, 0xab, 0x3a, 0x29, 0xa0, 0x5b, 0xc2, 0x39, 0x09, 0xdc, 0x9d,
	0xce, 0xbc, 0x86, 0x96, 0xd2, 0x48, 0x0b, 0x89, 0x71, 0x30, 0x6a, 0x4c, 0x42, 0x1e, 0xed, 0xcb,
	0x0c, 0xd9, 0x10, 0x3a, 0x07, 0x37, 0x89, 0x71, 0xd3, 0xb7, 0xda, 0xe5, 0x41, 0x86, 0xc9, 0x0b,
	0x9c, 0x97, 0x69, 0x73, 0x51, 0x14, 0x64, 0x9e, 0x49, 0x21, 0xeb, 0x41, 0x20, 0xd1, 0x07, 0x86,
	0x3c, 0x90, 0xc8, 0x66, 0x00, 0x52, 0x6d, 0x75, 0xee, 0x25, 0x3d, 0xbc, 0x7b, 0xb4, 0x48, 0x56,
	0xb5, 0xf8, 0xd1, 0x58, 0xb2, 0xac, 0x83, 0x39, 0xe5, 0xdb, 0x5f, 0xe0, 0x1b, 0x08, 0xf3, 0xbd,
	0x5b, 0xe0, 0xdd, 0x58, 0x85, 0xbc, 0x37, 0x46, 0x9b, 0xb9, 0x57, 0xdb, 0xf7, 0xd9, 0x15, 0x44,
	0x86, 0xec, 0xa6, 0x70, 0x7e, 0xfd, 0x0e, 0x3f, 0x54, 0x89, 0xaa, 0x65, 0x90, 0xcf, 0x18, 0x57,
	0x19, 0xdd, 0xe9, 0xe5, 0x1f, 0x4b, 0x66, 0xf8, 0x7f, 0xa7, 0xa7, 0x7a, 0x9e, 0xbf, 0xac, 0x13,
	0xf3, 0x7e, 0x14, 0x82, 0x63, 0x85, 0xbb, 0x31, 0x0c, 0xed, 0xce, 0x3a, 0x5a, 0xd9, 0x74, 0x25,
	0xde, 0x65, 0x05, 0x28, 0x9f, 0xe1, 0x6b, 0x54, 0x7e, 0x97, 0x91, 0x7f, 0x78, 0xb3, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0x76, 0xba, 0x73, 0xa6, 0x02, 0x00, 0x00,
}
